secrets:
  # strings and file contents are automatically base64 encoded
  ssh-creds:
    data:
      ssh.key: "ssh-rsa AAAAB3N.....uFo42 your@key.comment"
    files:
      id-rsa.pub: ci/files/id-rsa.pub

jobs:
  - name: print-secret
    schedule: "*/5 * * * *"
    command: ["cat", "/secrets/ssh-cred/ssh.key", "/secrets/ssh-cred/id-rsa.pub"]
